# set prefix to '`', but keep 'ctrl-b' too
set -g prefix '`'
bind-key '`' send-prefix
set-option -g prefix2 C-b

# easy reload ~/.tmux.conf
bind-key r source-file ~/.tmux.conf

# split pane commands                                                            
bind-key | split-window -h -c '#{pane_current_path}'                             
bind-key - split-window -v -c '#{pane_current_path}'                             
                                                                                 
# cycle through panes                                                            
set-option -g repeat-time 500 #milliseconds                                      
bind-key -r p select-pane -t :.+                                                 
bind-key -r P select-pane -t :.-  

# set window and pane index to 1 (0 by default) for easier direct access
set-option -g base-index 1
setw -g pane-base-index 1

# move between windows and sessions
bind-key -r h previous-window
bind-key -r j switch-client -n
bind-key -r k switch-client -p
bind-key -r l next-window

# STYLE

# Pane seperation colors, i.e., lines between panes
set -g pane-active-border-style 'fg=colour243'
set -g pane-border-style 'fg=colour236'

# Brighter text for active window pane
set -g window-style 'fg=colour245'
set -g window-active-style 'fg=colour252'

# Add padding to window names, and visual flag for window activity
set-option -g window-status-format ' #W#{?window_activity_flag,!,} ' 
set-option -g window-status-separator ''

# Default gray on gray status bar style
set-option -g status-style bg=colour236,fg=colour248

# Inactive window labels match the color of the status bar
set-window-option -g window-status-style bg=colour236,fg=colour248

# Active window label is slightly highlighted. Append -Z if a pane is zoomed.
set-window-option -g window-status-current-style bg=colour24,fg=colour14
set-window-option -g window-status-current-style bg=colour239,fg=colour251
set-option -g window-status-current-format ' #W#{?window_zoomed_flag,-Z,} '

# Left status
set -g status-left "#[bg=colour239,fg=colour252]"

# Right status
set -g status-right "#[bg=colour238,fg=colour244] %d %b %H:%M "
